### ISSUE TITLE
pre-commit hook

### ISSUE THREAD

**Issue by dycw** [tomcatling/black-nb#54]
Hi, I was wondering if it is possible to have this as a [pre-commit](https://pre-commit.com/) hook?

**Comment by MarcoGorelli** [comment]
@dycw in case it's useful to you, you could use `nbqa` for that:

```yaml
- repo: https://github.com/nbQA-dev/nbQA
  rev: 0.3.5
  hooks:
    - id: nbqa-black
      args: [--nbqa-mutate]
```
