### ISSUE TITLE
black[jupyter]

### ISSUE THREAD

**Issue by whitead** [tomcatling/black-nb#67]
I believe black has separated its jupyter part into `black[jupyter]`, so maybe the dependency for this project should be `black[jupyter]` instead?

**Comment by liamcoatman** [comment]
It looks like as of `21.8b0` `black` supports formatting Jupyter notebooks. How they handle things like Jupyter magics looks a lot more sophisticated than what we do, so people should almost certainly use that over our tool.

**Comment by whitead** [comment]
I kind of like this tool though, because it can strip output. I use it currently in a pre-commit hook like so:

```yml
repos:
  - repo: https://github.com/tomcatling/black-nb
    rev: 0.5.0
    hooks:
      - id: black-nb
        description: strip output and black source
        additional_dependencies: ['black[jupyter]']
        args: ["--clear-output"]
```

`black` currently just gives-up on notebooks now with their latest changes and request installing `black[jupyer]`. I'll create a PR for it.
